# Generated by Django 4.2.1 on 2023-08-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タイトル")),
                ("number", models.IntegerField(verbose_name="章番号")),
                ("is_free", models.BooleanField(default=True, verbose_name="無料かどうか")),
                (
                    "product_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="StripeProductId"
                    ),
                ),
                (
                    "price_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="StripePriceId"
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="価格")),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="customer_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="StripeCustomerId"
            ),
        ),
    ]
