# Generated by Django 4.2.1 on 2023-08-14 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_chapter_user_customer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="number",
        ),
    ]
