# Generated by Django 4.2.1 on 2023-08-15 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_chapter_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("price", models.IntegerField(blank=True, null=True, verbose_name="取引金額")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.chapter",
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "決済ログ",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("card_number", models.CharField(max_length=4, verbose_name="カード番号下四桁")),
                ("ex_year", models.CharField(max_length=2, verbose_name="カード有効期限(年)")),
                ("ex_month", models.CharField(max_length=2, verbose_name="カード有効期限(月)")),
                (
                    "payment_method_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="PaymentMethodId"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_card",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "カード情報",
            },
        ),
    ]
